language: cpp
sudo: false
notifications:
  email: false
compiler:
  - gcc
addons:
  apt_packages: "curl"
before_install:
  # Get CMake 2.8
  - wget https://github.com/Viq111/travis-container-packets/releases/download/cmake-2.8.12/cmake.tar.bz2
  - tar -xjf cmake.tar.bz2
  - rm cmake.tar.bz2
  - export PATH=$(pwd)/cmake/bin:$PATH
  # Get GCC 4.8
  - wget https://github.com/Viq111/travis-container-packets/releases/download/gcc-4.8.2/gcc.tar.bz2
  - tar -xjf gcc.tar.bz2
  - rm gcc.tar.bz2
  - export PATH=$(pwd)/gcc/bin:$PATH
  - cp ./gcc/bin/gcc ./gcc/bin/cc
  - export LIBRARY_PATH=$(pwd)/gcc/lib64
  - export LD_LIBRARY_PATH=$(pwd)/gcc/lib64:$LD_LIBRARY_PATH
  - export CPLUS_INCLUDE_PATH=$(pwd)/gcc/include/c++/4.8.2
  - export CC=$(pwd)/gcc/bin/gcc
  - echo 'Compiling with:'
  - $CXX --version
  - echo 'CMake version:'
  - cmake --version
  # Get SVN
  - sh build_svn.sh
script: 
  - sh build_clang.sh
os:
  - linux
